### ISSUE TITLE
Can not start mdbook command

### ISSUE THREAD

**Issue by hoangvx** [rust-tieng-viet/rust-tieng-viet.github.io#26]
### Loại yêu cầu

Sai nội dung

### Nội dung

Hello,
i am new to rust, and new to mdbook too.
please help me this bug. i running on windows machine

![image](https://github.com/rust-tieng-viet/rust-tieng-viet.github.io/assets/24557490/648df0ce-6ab6-452f-8691-174a1b498698)

**Comment by duyet** [comment]
The error is due to missing `mdbook-linkcheck` deps. I have updated to included it, so please check out the latest `main` branch and try again. Thank you
